# Generated by Django 4.0.2 on 2022-02-23 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Watch Date')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.favorite')),
            ],
        ),
    ]
